#include <iostream>
#include <cmath>
#include "bool.h"

int main()
{
    std::cout << "f1 = ";
    bool  f1 = is_pos(4);
    std::cout << f1 << std::endl;
    bool f2 = is_not_even(6);
    std::cout << "f2 = ";
    std::cout << f2 << std::endl;
    std::cout << "f3 = ";
    bool f3 = is_pos(6);
    std::cout << f3 << std::endl;
    std::cout << "f4 = ";
    bool f4 = more_than_2(4) && less_or_equal_3(3);
    std::cout << f4 << std::endl;
    std::cout << "f5 = ";
    bool f5 = more_or_equal_0(0) && less_than_minus_2(-3);
    std::cout << f5 << std::endl;
    std::cout << "f6 = ";
    bool f6 = less_num (less_num (6, 8), 4);
    std::cout << f6 << std::endl;
    std::cout << "f7 = ";
    bool f7 = min(min(4, 2), 3);
    std::cout << f7 << std::endl;
    std::cout << "f8 = ";
    bool  f8 = is_not_even(9) && is_not_even(3);
    std::cout << f8 << std::endl;
    std::cout << "f9 = ";
    bool f9 = is_not_even(4) || is_not_even(4);
    std::cout << f9 << std::endl;
    std::cout << "f10 = ";
    bool  f10 = is_not_even(4) ^ is_not_even(3);
    std::cout << f10 << std::endl;
    std::cout << "f12 = ";
    bool f12 = is_pos(4) && is_pos(8) && is_pos(-9);
    std::cout << f12 << std::endl;
    std::cout << "f13 = ";
    bool f13 = is_pos(4) || is_pos(8) || is_pos(-9);
    std::cout << f13 << std::endl;
    std::cout << "f14 = ";
    bool  f14 = is_pos(4) ^ is_pos(8) ^ is_pos(9);
    std::cout << f14 << std::endl;
    std::cout << "f15 = ";
    bool  f15 = (is_pos(4) ^ is_pos(8)) || (is_pos(-9) ^ is_pos(9)) || (is_pos(-9) ^ is_pos(-9));
    std::cout << f15 << std::endl;
    std::cout << "f16 = ";
    bool  f16 = is_pos(46) && two_valued (-46);
    std::cout << f16 << std::endl;
    std::cout << "f17 = ";
    bool f17 = is_not_even(45) && two_valued (45);
    std::cout << f17 << std::endl;
    bool f18 = the_same_pair(4, 5, 5);
    std::cout << "f18 = ";
    std::cout << f18 << std::endl;
    std::cout << "f19 = ";
    bool  f19 = is_not_the_same_pair(9, 9, 9);
    std::cout << f19 << std::endl;
    std::cout << "f20 = ";
    bool  f20 = all_not_the_same_pair(4, 3, 9);
    std::cout << f20 << std::endl;
    std::cout << "f21 = ";
    bool  f21 = ascending_sequense(1, 2, 3);
    std::cout << f21 <<std::endl;
    std::cout << "f22 = ";
    bool  f22 = ascending_sequense(3,2,1) || decreasing_sequense(3, 2, 1);
    std::cout << f22 <<std::endl;
    std::cout << "f23 = ";
    bool  f23 = polindrom_6(655556);
    std::cout << f23 << std::endl;
    std::cout << "f23_2 = ";
    bool f23_2 = polindrom_4(3663);
    std::cout << f23_2 << std::endl;
    std::cout << "f24 = ";
    bool f24 = vesh(1, 2, -2);
    std::cout << f24 << std::endl;
    std::cout << "f25 = ";
    bool f25 = second_chet(-5, 5);
    std::cout << f25 << std::endl;
    std::cout << "f26 = ";
    bool f26 = fourth_chet(5, -5);
    std::cout << f26 << std::endl;
    std::cout << "f27 = ";
    bool f27 = second_and_third_chet(-5, 5);
    std::cout << f27 << std::endl;
    std::cout << "f28 = ";
    bool f28 = first_and_fourth_chet(5, -5);
    std::cout << f28 << std::endl;
    std::cout << "f29 = ";
    bool f29 = coord(1, 2, 3 ,4 , 6 ,8);
    std::cout << f29 << std::endl;
    std::cout << "f30 = ";
    bool f30 = equilateral_triangle(4, 4, 4);
    std::cout << f30 << std::endl;
    std::cout << "f31 = ";
    bool f31 = isosceles_triangle(4, 4, 5);
    std::cout << f31 << std::endl;
    std::cout << "f32 = ";
    bool f32 = right_traingle(4, 2, 4);
    std::cout << f32 << std::endl;
    std::cout << "f33 = ";
    bool f33 = abc(4, 6, 8);
    std::cout << f33 << std::endl;
    std::cout << "f34 = ";
    bool f34 = chess_white(4, 4);
    std::cout << f34 << std::endl;
    bool f35 = one_color_chess(2, 4, 6, 2);
    std::cout << f35 << std::endl;
    return 0;
}
